spring:
  application:
    name: laislevi

  datasource:
    url: jdbc:postgresql://localhost:5432/casamento
    username: postgres
    password: B@ss10051997

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show_sql: true